
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2024"
name = "image_processing"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
image = "0.25"
image_hasher = "2.0"
fastembed = "4.4.0"
kamadak-exif = "0.5"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
